server:
  type: default
  maxThreads: 2000
  applicationConnectors:
    - type: http
      port: 8080
  requestLog:
    appenders:
        - type: file
          currentLogFilename: ./access.log
          threshold: ALL
          archive: true
          archivedLogFilenamePattern: ./access-%d.log
          archivedFileCount: 5
          timeZone: UTC

logging:
  level: WARN